//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class landDistrict
    {
        public int DistrictId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int ProvinceId { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual landProvince landProvince { get; set; }
    }
}
