//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtSubstituteDetail
    {
        public int SubstituteDetailId { get; set; }
        public Nullable<int> SubstituteId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
