//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtSubstitute
    {
        public int SubstituteId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string AppName { get; set; }
        public string AppCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
