//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtUnitManager
    {
        public int UnitManagerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
