//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qtUser()
        {
            this.shAboutus = new HashSet<shAboutu>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserLogin { get; set; }
        public string Password { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ImageFile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual qtDepartment qtDepartment { get; set; }
        public virtual qtPosition qtPosition { get; set; }
        public virtual qtUnit qtUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shAboutu> shAboutus { get; set; }
    }
}
