//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtUserRole
    {
        public int UserRoleId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Application { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual qtDepartment qtDepartment { get; set; }
        public virtual qtPosition qtPosition { get; set; }
        public virtual qtRole qtRole { get; set; }
        public virtual qtUnit qtUnit { get; set; }
    }
}
