//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtUserConfigDetail
    {
        public int UserConfigDetailId { get; set; }
        public Nullable<int> UserConfigId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
