//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shAboutu
    {
        public string AboutGuid { get; set; }
        public int AboutId { get; set; }
        public string AboutTitle { get; set; }
        public string MetaTitle { get; set; }
        public string AboutName { get; set; }
        public string AboutContent { get; set; }
        public Nullable<int> Year { get; set; }
        public string Sign { get; set; }
        public string ImageUrl { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual qtUser qtUser { get; set; }
    }
}
