//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shComment
    {
        public string CommentGuid { get; set; }
        public int CommentId { get; set; }
        public string MemberGuiId { get; set; }
        public string ProductGuid { get; set; }
        public string Email { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Contents { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> LaDaXem { get; set; }
    
        public virtual shMember shMember { get; set; }
        public virtual shProduct shProduct { get; set; }
    }
}
