//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shGoodReceiptIsuue
    {
        public string ReceiptIsuueGuid { get; set; }
        public int ReceiptIssueId { get; set; }
        public Nullable<int> Phieu { get; set; }
        public string ReceiptIsuueName { get; set; }
        public string SKU { get; set; }
        public Nullable<int> MaKho { get; set; }
        public string TenKho { get; set; }
        public Nullable<int> LoaiPhieu { get; set; }
        public string MaDonHang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
