//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shGoodReceiptIsuueDetail
    {
        public string ReceiptIsuueDetailGuid { get; set; }
        public int ReceiptIsuueDetailId { get; set; }
        public string ReceiptIsuueGuid { get; set; }
        public string ProductGuid { get; set; }
        public string SectionGuid { get; set; }
        public string SizeGuid { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Phieu { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
