//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shMember()
        {
            this.shComments = new HashSet<shComment>();
            this.shOrders = new HashSet<shOrder>();
        }
    
        public string MemberGuiId { get; set; }
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberLogin { get; set; }
        public string Password { get; set; }
        public string ImageFile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Phone { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> LaDaXem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shComment> shComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shOrder> shOrders { get; set; }
    }
}
