//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shNew
    {
        public string NewGuiId { get; set; }
        public int NewId { get; set; }
        public string TitleNew { get; set; }
        public string MetaTitle { get; set; }
        public string Descriptions { get; set; }
        public string ImageFile { get; set; }
        public string Summary { get; set; }
        public string Contents { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
