//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopOnlineDb : DbContext
    {
        public ShopOnlineDb()
            : base("name=ShopOnlineDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<landDistrict> landDistricts { get; set; }
        public virtual DbSet<landProvince> landProvinces { get; set; }
        public virtual DbSet<landQuanHuyen> landQuanHuyens { get; set; }
        public virtual DbSet<landTinhThanh> landTinhThanhs { get; set; }
        public virtual DbSet<LoaiPhieuNhap> LoaiPhieuNhaps { get; set; }
        public virtual DbSet<qtDepartment> qtDepartments { get; set; }
        public virtual DbSet<qtPosition> qtPositions { get; set; }
        public virtual DbSet<qtRole> qtRoles { get; set; }
        public virtual DbSet<qtSubstitute> qtSubstitutes { get; set; }
        public virtual DbSet<qtSubstituteDetail> qtSubstituteDetails { get; set; }
        public virtual DbSet<qtUnitManager> qtUnitManagers { get; set; }
        public virtual DbSet<qtUnit> qtUnits { get; set; }
        public virtual DbSet<qtUserConfig> qtUserConfigs { get; set; }
        public virtual DbSet<qtUserConfigDetail> qtUserConfigDetails { get; set; }
        public virtual DbSet<qtUserRole> qtUserRoles { get; set; }
        public virtual DbSet<qtUser> qtUsers { get; set; }
        public virtual DbSet<shAboutu> shAboutus { get; set; }
        public virtual DbSet<shAgent> shAgents { get; set; }
        public virtual DbSet<shBanner> shBanners { get; set; }
        public virtual DbSet<shCategory> shCategories { get; set; }
        public virtual DbSet<shCategoryImage> shCategoryImages { get; set; }
        public virtual DbSet<shColor> shColors { get; set; }
        public virtual DbSet<shComment> shComments { get; set; }
        public virtual DbSet<shGoodReceiptIsuue> shGoodReceiptIsuues { get; set; }
        public virtual DbSet<shGoodReceiptIsuueDetail> shGoodReceiptIsuueDetails { get; set; }
        public virtual DbSet<shMember> shMembers { get; set; }
        public virtual DbSet<shNew> shNews { get; set; }
        public virtual DbSet<shOrderDetail> shOrderDetails { get; set; }
        public virtual DbSet<shOrderHistory> shOrderHistories { get; set; }
        public virtual DbSet<shPrice> shPrices { get; set; }
        public virtual DbSet<shProductImage> shProductImages { get; set; }
        public virtual DbSet<shProduct> shProducts { get; set; }
        public virtual DbSet<shProductSet> shProductSets { get; set; }
        public virtual DbSet<shSaleDetail> shSaleDetails { get; set; }
        public virtual DbSet<shSetSize> shSetSizes { get; set; }
        public virtual DbSet<shSex> shSexes { get; set; }
        public virtual DbSet<shIdeaCustomer> shIdeaCustomers { get; set; }
        public virtual DbSet<shOrder> shOrders { get; set; }
        public virtual DbSet<shSale> shSales { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
    }
}
