//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shOrder()
        {
            this.shOrderDetails = new HashSet<shOrderDetail>();
        }
    
        public string OrderGuid { get; set; }
        public int OrderId { get; set; }
        public string OrderName { get; set; }
        public string MemberGuid { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<decimal> FeeShip { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<bool> LaDaXem { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual shMember shMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shOrderDetail> shOrderDetails { get; set; }
    }
}
