//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shPrice
    {
        public string PriceGuid { get; set; }
        public int PriceId { get; set; }
        public string ProductGuid { get; set; }
        public string SectionGuid { get; set; }
        public string SizeGuid { get; set; }
        public string PriceName { get; set; }
        public string MetaTitle { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual shSetSize shSetSize { get; set; }
    }
}
