//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shProductImage
    {
        public string ProductImageGuid { get; set; }
        public int ProductImageId { get; set; }
        public string ProductGuid { get; set; }
        public string FileName { get; set; }
        public string FileNameGoc { get; set; }
        public string ProductImageCategory { get; set; }
        public string Image { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual shProduct shProduct { get; set; }
    }
}
