//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shProductSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shProductSet()
        {
            this.shSetSizes = new HashSet<shSetSize>();
        }
    
        public string SectionGuid { get; set; }
        public int SectionId { get; set; }
        public string ProductGuid { get; set; }
        public string SectionName { get; set; }
        public string MetaTitle { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Inventory { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual shProduct shProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shSetSize> shSetSizes { get; set; }
    }
}
