//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shSale()
        {
            this.shSaleDetails = new HashSet<shSaleDetail>();
        }
    
        public string SaleGuid { get; set; }
        public int SaleId { get; set; }
        public string SaleDetailGuid { get; set; }
        public string SaleName { get; set; }
        public string SaleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CachTinhGiaTriKhuyenMai { get; set; }
        public string GiaTri { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> DieuKienApDung { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MetaTitle { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shSaleDetail> shSaleDetails { get; set; }
    }
}
