//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shSetSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shSetSize()
        {
            this.shPrices = new HashSet<shPrice>();
            this.shOrderDetails = new HashSet<shOrderDetail>();
        }
    
        public string SizeGuid { get; set; }
        public int SizeId { get; set; }
        public string ProductGuid { get; set; }
        public string SectionGuid { get; set; }
        public string SizeName { get; set; }
        public Nullable<decimal> PriceCurrent { get; set; }
        public string Stuff { get; set; }
        public string ParentId { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> PercentCurrent { get; set; }
        public Nullable<decimal> PriceAfterPercents { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Inventory { get; set; }
        public Nullable<int> SizeStatus { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shPrice> shPrices { get; set; }
        public virtual shProductSet shProductSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shOrderDetail> shOrderDetails { get; set; }
    }
}
