//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ThongBaoId { get; set; }
        public string NoiDungThongBao { get; set; }
        public string NoiDungCongViec { get; set; }
        public string LienKet { get; set; }
        public Nullable<int> NguoiThongBaoID { get; set; }
        public Nullable<int> NguoiNhanThongBaoId { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public string MaLoaiThongBao { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public string OrderGuid { get; set; }
    }
}
